### ISSUE TITLE
Should the 2D v 3D examples be in different tabs?

### ISSUE THREAD

**Issue by nwolek** [nwolek/vbap#3]
I wonder if the initial tab for the help file should just show the 2D define_loudspeakers message, then we move the 3D message to a new tab. There may not be much to demo there other than the fact that users can define them, but it would simplify the presentation on the main page.

**Comment by jln-** [comment]
I was wondering about it too. So I agree and will fix this ASAP.

**Comment by jln-** [comment]
Done in ed8c4eed68f48c12a7478991e0470a132cfd2de2
