### ISSUE TITLE
resize help patch to fit smaller screens

### ISSUE THREAD

**Issue by nwolek** [nwolek/vbap#8]
patch does not fit on my MacBook Pro (Retina, Mid 2012) screen

**Comment by nwolek** [comment]
@jln- and/or @sone - Please pull the latest commit on master and let me know if my changes to the help patch make sense.

**Comment by jln-** [comment]
They make perfect sense. Thanks Nathan !

**Comment by nwolek** [comment]
Thanks for confirming. I'm closing the issue now.
